### PR TITLE
Add ability to only rebase without fetching from remote.

### PR DESCRIPTION
**Pull request by nlutsenko**
Found this super helpful for day-to-day workflow, when some branch was just pushed upstream and I want all other local branches to have this change.

### CODE REVIEW

**Comment by nlutsenko** [comment]
@aanand ping ping
Let me know what you think about this. Would love to change it however you see fit.

**Comment by aanand** [comment]
So this is basically equivalent to doing a `git fetch` with `--prune` and `--all` appended according to git-up's configuration, right?

I'm not sure it adds enough value to be a feature of git-up vs. the user just running `git fetch`.

**Comment by nlutsenko** [comment]
This is actually the other way around :)
It allows to use `git-up` awesome rebase code to skip `git fetch` and simply rebase all local branches.

The workflow where it's helpful:
- 5 branches tracking origin/master
- `git push` 3 commits
- `git up --local`
- 4 branches get rebased automatically without fetching from remote

**Comment by nlutsenko** [comment]
@aanand Ping :D

**Comment by aanand** [comment]
OK, I think I'm in favour of this feature, but could you rename the flag and the ivar?

I think it'd be best to call the flag `--no-fetch`, and call the ivar `@fetch` (inverting the logic).

**Comment by nlutsenko** [comment]
Yay! Will update, sure.

**Comment by nlutsenko** [comment]
@aanand Just updated with reversed logic.

**Comment by aanand** [comment]
Nice.

**Pull request merged**
